# Generated by Django 4.1.1 on 2022-11-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogproduct',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
