# Generated by Django 4.1.1 on 2022-12-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_alter_dogproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogproduct',
            name='image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
