# Generated by Django 4.1.1 on 2022-12-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_alter_dogproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogproduct',
            name='desc',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
