# Generated by Django 4.1.1 on 2022-12-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0005_catproduct_alter_dogproduct_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catproduct',
        ),
    ]
