# Generated by Django 4.1.1 on 2022-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_delete_catproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
