# Generated by Django 4.1.1 on 2022-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0007_dogproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
