# Generated by Django 4.1.1 on 2023-01-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0008_alter_dogproduct_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogproduct',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
