# Generated by Django 4.1.1 on 2022-12-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='cproduct_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='dproduct_qty',
            field=models.IntegerField(default=1),
        ),
    ]
