# Generated by Django 4.1.1 on 2022-12-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_qty_cart_cproduct_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cproduct',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cproduct_qty',
        ),
    ]
