# Generated by Django 4.1.1 on 2022-12-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_cproduct_remove_cart_cproduct_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dproduct_qty',
            field=models.IntegerField(),
        ),
    ]
