# Generated by Django 4.1.1 on 2023-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_status_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='order',
        ),
        migrations.AddField(
            model_name='pay',
            name='cardno',
            field=models.CharField(default=1111222233334444, max_length=20),
        ),
        migrations.AddField(
            model_name='pay',
            name='cvv',
            field=models.CharField(default='234', max_length=20),
        ),
        migrations.AddField(
            model_name='pay',
            name='month',
            field=models.CharField(default='September', max_length=20),
        ),
        migrations.AddField(
            model_name='pay',
            name='nameoncard',
            field=models.CharField(default='cart.models', max_length=150),
        ),
        migrations.AddField(
            model_name='pay',
            name='year',
            field=models.CharField(default='2020', max_length=20),
        ),
    ]
