# Generated by Django 4.1.1 on 2023-01-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0009_alter_dogproduct_options'),
        ('cart', '0008_pay_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dog.dogproduct'),
        ),
    ]
