# Generated by Django 4.1.1 on 2023-01-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_pay_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
    ]
