# Generated by Django 4.1.1 on 2023-01-22 08:10

from django.db import migrations, models
import django.db.models.deletion
import dog.models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0009_alter_dogproduct_options'),
        ('cart', '0011_alter_pay_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='products',
        ),
        migrations.AddField(
            model_name='pay',
            name='product',
            field=models.ForeignKey(default=dog.models.Dogproduct, on_delete=django.db.models.deletion.CASCADE, to='dog.dogproduct'),
        ),
    ]
