# Generated by Django 4.1.1 on 2023-01-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_pay_products_pay_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='product',
        ),
    ]
